var express = require('express');
var app = express();

// Set some express config up
app.set('view engine', 'jade');
app.use(express.bodyParser());
app.use(express.logger('dev'));
app.set('views', __dirname + '/views');

app.get('/', function(req, res)
{
    res.render('layout');
});

app.post('/FormPost', function(req, res)
{
    res.send('<html><head><title>Node.js for fun and profit</title></head><body><h2>Node.js is server-side Javascript</h2>Hello, ' + req.body.NameTextBox + '<br/>I am generated by Node.js, which is server-side Javascript.<br/><a href="/">Go again.</a></body></html>');
});
app.listen(process.env.port || 1337);